[jfrog-platform] 10.17.0 release

diff --git a/stable/jfrog-platform/templates/migration-hook.yaml b/stable/jfrog-platform/templates/migration-hook.yaml
--- a/stable/jfrog-platform/templates/migration-hook.yaml
+++ b/stable/jfrog-platform/templates/migration-hook.yaml
@@ -68,8 +68,8 @@ roleRef:
 ---
 {{- if .Values.rabbitmq.enabled }}
 {{- if .Values.rabbitmq.migration.enabled }}
-apiVersion: v1
-kind: Pod
+apiVersion: batch/v1
+kind: Job
 metadata:
   labels:
     app: {{ template "jfrog-platform.name" . }}
@@ -81,37 +81,45 @@ metadata:
     "helm.sh/hook": "pre-upgrade"
     "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
 spec:
-  serviceAccountName: {{ template "jfrog-platform.rabbitmq.migration.serviceAccountName" . }}
-  {{- if .Values.rabbitmq.podSecurityContext.enabled }}
-  securityContext: {{- omit .Values.rabbitmq.podSecurityContext "enabled" | toYaml | nindent 4 }}
-  {{- end }}
-  {{- if .Values.global.imagePullSecrets }}
-  {{- include "jfrog-platform.imagePullSecrets" . | indent 2 }}
-  {{- end }}
-  containers:
-    - name: pre-upgrade-container
-      image: "{{ include "jfrog-platform.getRegistryByService" (list . "migrationHook") }}/{{ .Values.rabbitmq.migration.image.repository }}:{{ .Values.rabbitmq.migration.image.tag }}"
-      imagePullPolicy: IfNotPresent
-      {{- if .Values.rabbitmq.containerSecurityContext.enabled }}
-      securityContext: {{- tpl (omit .Values.rabbitmq.containerSecurityContext "enabled" | toYaml) . | nindent 10 }}
+  template:
+    metadata:
+      labels:
+        app: {{ template "jfrog-platform.name" . }}
+        chart: {{ template "jfrog-platform.chart" . }}
+        heritage: {{ .Release.Service }}
+        release: {{ .Release.Name }}
+    spec:
+      serviceAccountName: {{ template "jfrog-platform.rabbitmq.migration.serviceAccountName" . }}
+      {{- if .Values.rabbitmq.podSecurityContext.enabled }}
+      securityContext: {{- omit .Values.rabbitmq.podSecurityContext "enabled" | toYaml | nindent 8 }}
       {{- end }}
-      command:
-        - sh
-        - -c
-        - |
-            #!/bin/sh
-            if [ "$(kubectl get pods -l "app.kubernetes.io/name={{ template "rabbitmq.name" . }}" -o jsonpath='{..status.conditions[?(@.type=="Ready")].status}')" = "True" ]; then
-                kubectl exec -it {{ .Release.Name }}-{{ template "rabbitmq.name" . }}-0 -- rabbitmqctl enable_feature_flag all
-                if [ "$?" -ne 0 ]; then
-                   echo "Failed to perform the migration. Please make sure to enable the feature flag in rabbitmq manually [rabbitmqctl enable_feature_flag all] "
-                   exit 1
+      {{- if .Values.global.imagePullSecrets }}
+      {{- include "jfrog-platform.imagePullSecrets" . | indent 6 }}
+      {{- end }}
+      containers:
+        - name: pre-upgrade-container
+          image: "{{ include "jfrog-platform.getRegistryByService" (list . "migrationHook") }}/{{ .Values.rabbitmq.migration.image.repository }}:{{ .Values.rabbitmq.migration.image.tag }}"
+          imagePullPolicy: IfNotPresent
+          {{- if .Values.rabbitmq.containerSecurityContext.enabled }}
+          securityContext: {{- tpl (omit .Values.rabbitmq.containerSecurityContext "enabled" | toYaml) . | nindent 12 }}
+          {{- end }}
+          command:
+            - sh
+            - -c
+            - |
+                #!/bin/sh
+                if [ "$(kubectl get pods -l "app.kubernetes.io/name={{ template "rabbitmq.name" . }}" -o jsonpath='{..status.conditions[?(@.type=="Ready")].status}')" = "True" ]; then
+                    kubectl exec -it {{ .Release.Name }}-{{ template "rabbitmq.name" . }}-0 -- rabbitmqctl enable_feature_flag all
+                    if [ "$?" -ne 0 ]; then
+                      echo "Failed to perform the migration. Please make sure to enable the feature flag in rabbitmq manually [rabbitmqctl enable_feature_flag all] "
+                      exit 1
+                    else
+                      echo Feature flags executed successfully!
+                    fi
                 else
-                   echo Feature flags executed successfully!
+                    echo "Rabbitmq pod is not in running state. Ignoring feature flag migration for rabbitmq"
                 fi
-            else
-                echo "Rabbitmq pod is not in running state. Ignoring feature flag migration for rabbitmq"
-            fi
-  restartPolicy: Never
-  terminationGracePeriodSeconds: 0
+      restartPolicy: Never
+      terminationGracePeriodSeconds: 0
 {{- end }}
 {{- end }}
