[jfrog-platform] 10.15.0 release

diff --git a/stable/jfrog-platform/templates/migration-hook.yaml b/stable/jfrog-platform/templates/migration-hook.yaml
--- a/stable/jfrog-platform/templates/migration-hook.yaml
+++ b/stable/jfrog-platform/templates/migration-hook.yaml
@@ -85,14 +85,32 @@ spec:
   {{- if .Values.rabbitmq.podSecurityContext.enabled }}
   securityContext: {{- omit .Values.rabbitmq.podSecurityContext "enabled" | toYaml | nindent 4 }}
   {{- end }}
+  {{- if .Values.global.imagePullSecrets }}
+  {{- include "jfrog-platform.imagePullSecrets" . | indent 2 }}
+  {{- end }}
   containers:
     - name: pre-upgrade-container
-      image: releases-docker.jfrog.io/bitnami/kubectl:1.24.12
+      image: "{{ include "jfrog-platform.getRegistryByService" (list . "migrationHook") }}/{{ .Values.rabbitmq.migration.image.repository }}:{{ .Values.rabbitmq.migration.image.tag }}"
       imagePullPolicy: IfNotPresent
       {{- if .Values.rabbitmq.containerSecurityContext.enabled }}
       securityContext: {{- tpl (omit .Values.rabbitmq.containerSecurityContext "enabled" | toYaml) . | nindent 10 }}
       {{- end }}
-      command: ['sh', '-c', 'kubectl exec -it {{ .Release.Name }}-{{ template "rabbitmq.name" . }}-0 -- rabbitmqctl enable_feature_flag all ; if [ "$?" -ne 0 ]; then echo "Failed to perform the migration. Please make sure to enable the feature flag in rabbitmq manually [rabbitmqctl enable_feature_flag all] "; exit 1; fi' ]
+      command:
+        - sh
+        - -c
+        - |
+            #!/bin/sh
+            if [ "$(kubectl get pods -l "app.kubernetes.io/name={{ template "rabbitmq.name" . }}" -o jsonpath='{..status.conditions[?(@.type=="Ready")].status}')" = "True" ]; then
+                kubectl exec -it {{ .Release.Name }}-{{ template "rabbitmq.name" . }}-0 -- rabbitmqctl enable_feature_flag all
+                if [ "$?" -ne 0 ]; then
+                   echo "Failed to perform the migration. Please make sure to enable the feature flag in rabbitmq manually [rabbitmqctl enable_feature_flag all] "
+                   exit 1
+                else
+                   echo Feature flags executed successfully!
+                fi
+            else
+                echo "Rabbitmq pod is not in running state. Ignoring feature flag migration for rabbitmq"
+            fi
   restartPolicy: Never
   terminationGracePeriodSeconds: 0
 {{- end }}
